name: CI

on:
  push:
    branches: [ main, develop, test ]
  pull_request:
    branches: [ main, develop, test ]

jobs:
  build:
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        
    - name: Set up Python
      uses: actions/setup-python@v5
        
    - name: Create and activate virtual environment
      run: |
        python -m venv canwaifu # 解决 pep668
        source canwaifu/bin/activate
        python -m pip install --upgrade pip
        
    - name: Install dependencies
      run: |
        source canwaifu/bin/activate
        pip install platformio
        
    - name: Install platformIO libraries
      run: |
        source canwaifu/bin/activate
        pio lib install
        
    - name: Run PlatformIO
      run: |
        source canwaifu/bin/activate
        platformio run